# Generated by Django 4.0.1 on 2022-01-14 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0002_poseimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='poseimage',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
