# Generated by Django 4.0.1 on 2022-01-14 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0003_poseimage_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PoseImage',
        ),
    ]
