# Generated by Django 4.0.1 on 2022-01-14 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0004_delete_poseimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=150, null=True)),
                ('subject', models.CharField(max_length=150, null=True)),
                ('message', models.TextField()),
            ],
        ),
    ]
