# Generated by Django 4.0.1 on 2022-01-14 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0006_schedule_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='trainer_image',
            field=models.ImageField(blank=True, null=True, upload_to='trainerphoto'),
        ),
    ]
