# Generated by Django 4.0.1 on 2022-01-14 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0008_plan_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='blogphoto'),
        ),
    ]
