# Generated by Django 4.0.1 on 2022-01-14 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0009_blog_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100)),
            ],
        ),
    ]
