# Generated by Django 4.0.1 on 2022-01-16 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0013_social_remove_comment_post_delete_customer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='social',
            name='icon',
        ),
    ]
