# Generated by Django 4.0.1 on 2022-01-16 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0014_remove_social_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='price',
            name='plan',
        ),
        migrations.AddField(
            model_name='price',
            name='plan',
            field=models.ManyToManyField(to='health.Plan', verbose_name='plan'),
        ),
    ]
