# Generated by Django 4.0.1 on 2022-01-16 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0017_alter_price_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='plan',
            field=models.ManyToManyField(to='health.Plan'),
        ),
    ]
