# Generated by Django 4.0.1 on 2022-01-16 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0018_alter_price_plan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='price',
            name='plan',
        ),
        migrations.AddField(
            model_name='price',
            name='plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='health.plan'),
        ),
    ]
