# Generated by Django 4.0.1 on 2022-01-16 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0019_remove_price_plan_price_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health.plan'),
        ),
    ]
